<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
| GS1 Prefix ranges (GTIN-13 / EAN-13 and related identification keys).
| Source: https://www.gs1.org/standards/id-keys/company-prefix (retrieved 2026-06)
| Note: Prefixes identify the issuing GS1 Member Organisation, not country of origin.
| Prefixes 984-989: GSCN 25-302 (2025) — reserved for future GS1 coupon identification.
*/
$config['gtin_country_codes'] = array(
	array('prefix' => '0000000', 'country' => 'Restricted circulation numbers (within a company)'),
	array('prefix' => '0000001-0000099', 'country' => 'Unused (avoid collision with GTIN-8)'),
	array('prefix' => '00001-00009', 'country' => 'GS1 US'),
	array('prefix' => '0001-0009', 'country' => 'GS1 US'),
	array('prefix' => '001-019', 'country' => 'GS1 US'),
	array('prefix' => '020-029', 'country' => 'Restricted circulation numbers (geographic region, MO defined)'),
	array('prefix' => '030-039', 'country' => 'GS1 US'),
	array('prefix' => '040-049', 'country' => 'Restricted circulation numbers (within a company)'),
	array('prefix' => '050-059', 'country' => 'GS1 US (reserved for future use)'),
	array('prefix' => '060-139', 'country' => 'GS1 US'),
	array('prefix' => '200-299', 'country' => 'Restricted circulation numbers (geographic region, MO defined)'),
	array('prefix' => '300-379', 'country' => 'GS1 France'),
	array('prefix' => '380', 'country' => 'GS1 Bulgaria'),
	array('prefix' => '383', 'country' => 'GS1 Slovenija'),
	array('prefix' => '385', 'country' => 'GS1 Croatia'),
	array('prefix' => '387', 'country' => 'GS1 BIH (Bosnia-Herzegovina)'),
	array('prefix' => '389', 'country' => 'GS1 Montenegro'),
	array('prefix' => '400-440', 'country' => 'GS1 Germany'),
	array('prefix' => '450-459', 'country' => 'GS1 Japan'),
	array('prefix' => '460-469', 'country' => 'GS1 Russia'),
	array('prefix' => '470', 'country' => 'GS1 Kyrgyzstan'),
	array('prefix' => '471', 'country' => 'GS1 Chinese Taipei'),
	array('prefix' => '474', 'country' => 'GS1 Estonia'),
	array('prefix' => '475', 'country' => 'GS1 Latvia'),
	array('prefix' => '476', 'country' => 'GS1 Azerbaijan'),
	array('prefix' => '477', 'country' => 'GS1 Lithuania'),
	array('prefix' => '478', 'country' => 'GS1 Uzbekistan'),
	array('prefix' => '479', 'country' => 'GS1 Sri Lanka'),
	array('prefix' => '480', 'country' => 'GS1 Philippines'),
	array('prefix' => '481', 'country' => 'GS1 Belarus'),
	array('prefix' => '482', 'country' => 'GS1 Ukraine'),
	array('prefix' => '483', 'country' => 'GS1 Turkmenistan'),
	array('prefix' => '484', 'country' => 'GS1 Moldova'),
	array('prefix' => '485', 'country' => 'GS1 Armenia'),
	array('prefix' => '486', 'country' => 'GS1 Georgia'),
	array('prefix' => '487', 'country' => 'GS1 Kazakstan'),
	array('prefix' => '488', 'country' => 'GS1 Tajikistan'),
	array('prefix' => '489', 'country' => 'GS1 Hong Kong, China'),
	array('prefix' => '490-499', 'country' => 'GS1 Japan'),
	array('prefix' => '500-509', 'country' => 'GS1 UK'),
	array('prefix' => '520-521', 'country' => 'GS1 Association Greece'),
	array('prefix' => '528', 'country' => 'GS1 Lebanon'),
	array('prefix' => '529', 'country' => 'GS1 Cyprus'),
	array('prefix' => '530', 'country' => 'GS1 Albania'),
	array('prefix' => '531', 'country' => 'GS1 Macedonia'),
	array('prefix' => '535', 'country' => 'GS1 Malta'),
	array('prefix' => '539', 'country' => 'GS1 Ireland'),
	array('prefix' => '540-549', 'country' => 'GS1 Belgium & Luxembourg'),
	array('prefix' => '560', 'country' => 'GS1 Portugal'),
	array('prefix' => '569', 'country' => 'GS1 Iceland'),
	array('prefix' => '570-579', 'country' => 'GS1 Denmark'),
	array('prefix' => '590', 'country' => 'GS1 Poland'),
	array('prefix' => '594', 'country' => 'GS1 Romania'),
	array('prefix' => '599', 'country' => 'GS1 Hungary'),
	array('prefix' => '600-601', 'country' => 'GS1 South Africa'),
	array('prefix' => '603', 'country' => 'GS1 Ghana'),
	array('prefix' => '604', 'country' => 'GS1 Senegal'),
	array('prefix' => '605', 'country' => 'GS1 Uganda'),
	array('prefix' => '606', 'country' => 'GS1 Angola'),
	array('prefix' => '607', 'country' => 'GS1 Oman'),
	array('prefix' => '608', 'country' => 'GS1 Bahrain'),
	array('prefix' => '609', 'country' => 'GS1 Mauritius'),
	array('prefix' => '610', 'country' => 'Managed by GS1 Global Office (future MO)'),
	array('prefix' => '611', 'country' => 'GS1 Morocco'),
	array('prefix' => '613', 'country' => 'GS1 Algeria'),
	array('prefix' => '614', 'country' => 'Managed by GS1 Global Office (future MO)'),
	array('prefix' => '615', 'country' => 'GS1 Nigeria'),
	array('prefix' => '616', 'country' => 'GS1 Kenya'),
	array('prefix' => '617', 'country' => 'GS1 Cameroon'),
	array('prefix' => '618', 'country' => 'GS1 Côte d\'Ivoire'),
	array('prefix' => '619', 'country' => 'GS1 Tunisia'),
	array('prefix' => '620', 'country' => 'GS1 Tanzania'),
	array('prefix' => '621', 'country' => 'GS1 Syria'),
	array('prefix' => '622', 'country' => 'GS1 Egypt'),
	array('prefix' => '623', 'country' => 'Managed by GS1 Global Office (future MO)'),
	array('prefix' => '624', 'country' => 'GS1 Libya'),
	array('prefix' => '625', 'country' => 'GS1 Jordan'),
	array('prefix' => '626', 'country' => 'GS1 Iran'),
	array('prefix' => '627', 'country' => 'GS1 Kuwait'),
	array('prefix' => '628', 'country' => 'GS1 Saudi Arabia'),
	array('prefix' => '629', 'country' => 'GS1 Emirates'),
	array('prefix' => '630', 'country' => 'GS1 Qatar'),
	array('prefix' => '631', 'country' => 'GS1 Namibia'),
	array('prefix' => '632', 'country' => 'GS1 Rwanda'),
	array('prefix' => '640-649', 'country' => 'GS1 Finland'),
	array('prefix' => '680-681', 'country' => 'GS1 China'),
	array('prefix' => '690-699', 'country' => 'GS1 China'),
	array('prefix' => '700-709', 'country' => 'GS1 Norway'),
	array('prefix' => '729', 'country' => 'GS1 Israel'),
	array('prefix' => '730-739', 'country' => 'GS1 Sweden'),
	array('prefix' => '740', 'country' => 'GS1 Guatemala'),
	array('prefix' => '741', 'country' => 'GS1 El Salvador'),
	array('prefix' => '742', 'country' => 'GS1 Honduras'),
	array('prefix' => '743', 'country' => 'GS1 Nicaragua'),
	array('prefix' => '744', 'country' => 'GS1 Costa Rica'),
	array('prefix' => '745', 'country' => 'GS1 Panama'),
	array('prefix' => '746', 'country' => 'GS1 Republica Dominicana'),
	array('prefix' => '750', 'country' => 'GS1 Mexico'),
	array('prefix' => '754-755', 'country' => 'GS1 Canada'),
	array('prefix' => '758', 'country' => 'Managed by GS1 Global Office (future MO)'),
	array('prefix' => '759', 'country' => 'GS1 Venezuela'),
	array('prefix' => '760-769', 'country' => 'GS1 Switzerland'),
	array('prefix' => '770-771', 'country' => 'GS1 Colombia'),
	array('prefix' => '773', 'country' => 'GS1 Uruguay'),
	array('prefix' => '775', 'country' => 'GS1 Peru'),
	array('prefix' => '777', 'country' => 'GS1 Bolivia'),
	array('prefix' => '778-779', 'country' => 'GS1 Argentina'),
	array('prefix' => '780', 'country' => 'GS1 Chile'),
	array('prefix' => '784', 'country' => 'GS1 Paraguay'),
	array('prefix' => '786', 'country' => 'GS1 Ecuador'),
	array('prefix' => '789-790', 'country' => 'GS1 Brasil'),
	array('prefix' => '800-839', 'country' => 'GS1 Italy'),
	array('prefix' => '840-849', 'country' => 'GS1 Spain'),
	array('prefix' => '850', 'country' => 'GS1 Cuba'),
	array('prefix' => '858', 'country' => 'GS1 Slovakia'),
	array('prefix' => '859', 'country' => 'GS1 Czech'),
	array('prefix' => '860', 'country' => 'GS1 Serbia'),
	array('prefix' => '865', 'country' => 'GS1 Mongolia'),
	array('prefix' => '867', 'country' => 'GS1 DPRK'),
	array('prefix' => '868-869', 'country' => 'GS1 Türkiye'),
	array('prefix' => '870-879', 'country' => 'GS1 Netherlands'),
	array('prefix' => '880-881', 'country' => 'GS1 ROK'),
	array('prefix' => '883', 'country' => 'GS1 Myanmar'),
	array('prefix' => '884', 'country' => 'GS1 Cambodia'),
	array('prefix' => '885', 'country' => 'GS1 Thailand'),
	array('prefix' => '888', 'country' => 'GS1 Singapore'),
	array('prefix' => '890', 'country' => 'GS1 India'),
	array('prefix' => '893', 'country' => 'GS1 Vietnam'),
	array('prefix' => '894', 'country' => 'Managed by GS1 Global Office (future MO)'),
	array('prefix' => '896', 'country' => 'GS1 Pakistan'),
	array('prefix' => '899', 'country' => 'GS1 Indonesia'),
	array('prefix' => '900-919', 'country' => 'GS1 Austria'),
	array('prefix' => '930-939', 'country' => 'GS1 Australia'),
	array('prefix' => '940-949', 'country' => 'GS1 New Zealand'),
	array('prefix' => '950', 'country' => 'GS1 Global Office'),
	array('prefix' => '951', 'country' => 'GS1 Global Office (EPC General Manager Number)'),
	array('prefix' => '952', 'country' => 'Demonstrations and examples of the GS1 system'),
	array('prefix' => '955', 'country' => 'GS1 Malaysia'),
	array('prefix' => '958', 'country' => 'GS1 Macau, China'),
	array('prefix' => '960-969', 'country' => 'GS1 Global Office (GTIN-8)'),
	array('prefix' => '977', 'country' => 'Serial publications (ISSN)'),
	array('prefix' => '978-979', 'country' => 'Bookland (ISBN)'),
	array('prefix' => '980', 'country' => 'Refund receipts'),
	array('prefix' => '981-983', 'country' => 'GS1 coupon identification (common currency areas)'),
	array('prefix' => '984-989', 'country' => 'Reserved for future GS1 coupon identification'),
	array('prefix' => '99', 'country' => 'GS1 coupon identification'),
);
